[profile.release]
lto = "fat"
opt-level = 'z'
codegen-units = 1

# These 2 make the br compressed wasm a bit smaller.
# Using strip = "symbols" aka true breaks the client.
strip = "debuginfo"
panic = "abort"

[unstable]
# Slows down debug mode quite a bit TODO find a way to only enable in release mode.
# Requires the rust-src component. `rustup +nightly component add rust-src`
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
