[package]
name = "sprite_sheet"
workspace = ".."
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[dependencies]
serde = "1.0.130"
serde_json = "1.0.67"
glam = {version = "0.18", features = ["serde"]}